# Generated by Django 3.1.2 on 2020-10-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='peserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('domisili', models.CharField(max_length=100, null=True)),
                ('tanggal_lahir', models.CharField(max_length=50, null=True)),
                ('alasan', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('deskripsi', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='daftarPeserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kegiatanku.peserta')),
                ('sesuatu', models.ManyToManyField(to='kegiatanku.tags')),
            ],
        ),
    ]
