# Generated by Django 3.1.2 on 2020-10-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatanku', '0002_auto_20201023_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='nama',
            new_name='nama_kegiatan',
        ),
    ]
