# Generated by Django 3.1.2 on 2020-10-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatanku', '0004_auto_20201024_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peserta',
            name='alasan',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='tanggal_lahir',
        ),
        migrations.DeleteModel(
            name='daftarPeserta',
        ),
    ]
